# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\���ٽ�վ\doing.ui'
#
# Created: Sun Jul 12 21:08:37 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1052, 758)
        Dialog.setSizeGripEnabled(True)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 651, 551))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 631, 51))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pb_deldata = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pb_deldata.setObjectName(_fromUtf8("pb_deldata"))
        self.horizontalLayout.addWidget(self.pb_deldata)
        self.pb_scbjt = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pb_scbjt.setObjectName(_fromUtf8("pb_scbjt"))
        self.horizontalLayout.addWidget(self.pb_scbjt)
        self.pb_scfl = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pb_scfl.setObjectName(_fromUtf8("pb_scfl"))
        self.horizontalLayout.addWidget(self.pb_scfl)
        self.pb_scwz = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pb_scwz.setObjectName(_fromUtf8("pb_scwz"))
        self.horizontalLayout.addWidget(self.pb_scwz)
        self.pb_scxc = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pb_scxc.setObjectName(_fromUtf8("pb_scxc"))
        self.horizontalLayout.addWidget(self.pb_scxc)
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 240, 631, 51))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_4.addWidget(self.label_5)
        self.le_wzfl1 = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.le_wzfl1.setObjectName(_fromUtf8("le_wzfl1"))
        self.horizontalLayout_4.addWidget(self.le_wzfl1)
        self.pb_upwz1 = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pb_upwz1.setObjectName(_fromUtf8("pb_upwz1"))
        self.horizontalLayout_4.addWidget(self.pb_upwz1)
        self.le_wzfl2 = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.le_wzfl2.setObjectName(_fromUtf8("le_wzfl2"))
        self.horizontalLayout_4.addWidget(self.le_wzfl2)
        self.pb_upwz2 = QtGui.QPushButton(self.horizontalLayoutWidget_4)
        self.pb_upwz2.setObjectName(_fromUtf8("pb_upwz2"))
        self.horizontalLayout_4.addWidget(self.pb_upwz2)
        self.horizontalLayoutWidget_7 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(10, 120, 631, 51))
        self.horizontalLayoutWidget_7.setObjectName(_fromUtf8("horizontalLayoutWidget_7"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setMargin(0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget_7)
        self.label_4.setEnabled(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_7.addWidget(self.label_4)
        self.le_xcfl1 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.le_xcfl1.setObjectName(_fromUtf8("le_xcfl1"))
        self.horizontalLayout_7.addWidget(self.le_xcfl1)
        self.pb_upxc1 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.pb_upxc1.setObjectName(_fromUtf8("pb_upxc1"))
        self.horizontalLayout_7.addWidget(self.pb_upxc1)
        self.le_xcfl2 = QtGui.QLineEdit(self.horizontalLayoutWidget_7)
        self.le_xcfl2.setObjectName(_fromUtf8("le_xcfl2"))
        self.horizontalLayout_7.addWidget(self.le_xcfl2)
        self.pb_upxc2 = QtGui.QPushButton(self.horizontalLayoutWidget_7)
        self.pb_upxc2.setObjectName(_fromUtf8("pb_upxc2"))
        self.horizontalLayout_7.addWidget(self.pb_upxc2)
        self.horizontalLayoutWidget_8 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 180, 631, 51))
        self.horizontalLayoutWidget_8.setObjectName(_fromUtf8("horizontalLayoutWidget_8"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setMargin(0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget_8)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_8.addWidget(self.label_3)
        self.le_fl1 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.le_fl1.setObjectName(_fromUtf8("le_fl1"))
        self.horizontalLayout_8.addWidget(self.le_fl1)
        self.le_fl2 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.le_fl2.setObjectName(_fromUtf8("le_fl2"))
        self.horizontalLayout_8.addWidget(self.le_fl2)
        self.le_fl3 = QtGui.QLineEdit(self.horizontalLayoutWidget_8)
        self.le_fl3.setObjectName(_fromUtf8("le_fl3"))
        self.horizontalLayout_8.addWidget(self.le_fl3)
        self.pb_onebuild = QtGui.QPushButton(self.horizontalLayoutWidget_8)
        self.pb_onebuild.setObjectName(_fromUtf8("pb_onebuild"))
        self.horizontalLayout_8.addWidget(self.pb_onebuild)
        self.pte_jj = QtGui.QPlainTextEdit(self.tab)
        self.pte_jj.setGeometry(QtCore.QRect(10, 350, 631, 171))
        self.pte_jj.setUndoRedoEnabled(True)
        self.pte_jj.setOverwriteMode(False)
        self.pte_jj.setObjectName(_fromUtf8("pte_jj"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 300, 631, 51))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_3.addWidget(self.label)
        self.pb_upwz = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pb_upwz.setObjectName(_fromUtf8("pb_upwz"))
        self.horizontalLayout_3.addWidget(self.pb_upwz)
        self.pb_upjj = QtGui.QPushButton(self.horizontalLayoutWidget_3)
        self.pb_upjj.setObjectName(_fromUtf8("pb_upjj"))
        self.horizontalLayout_3.addWidget(self.pb_upjj)
        self.horizontalLayoutWidget_5 = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 60, 631, 51))
        self.horizontalLayoutWidget_5.setObjectName(_fromUtf8("horizontalLayoutWidget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pb_upsybj = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pb_upsybj.setObjectName(_fromUtf8("pb_upsybj"))
        self.horizontalLayout_5.addWidget(self.pb_upsybj)
        self.pb_smb = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pb_smb.setObjectName(_fromUtf8("pb_smb"))
        self.horizontalLayout_5.addWidget(self.pb_smb)
        self.pb_xmb = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pb_xmb.setObjectName(_fromUtf8("pb_xmb"))
        self.horizontalLayout_5.addWidget(self.pb_xmb)
        self.pb_zmb = QtGui.QPushButton(self.horizontalLayoutWidget_5)
        self.pb_zmb.setObjectName(_fromUtf8("pb_zmb"))
        self.horizontalLayout_5.addWidget(self.pb_zmb)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.formLayoutWidget = QtGui.QWidget(self.tab_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 521))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.formLayoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(80, 31))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.le_gsjc = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_gsjc.setMinimumSize(QtCore.QSize(0, 31))
        self.le_gsjc.setObjectName(_fromUtf8("le_gsjc"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.le_gsjc)
        self.label_8 = QtGui.QLabel(self.formLayoutWidget)
        self.label_8.setMinimumSize(QtCore.QSize(80, 31))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.le_hyfl = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_hyfl.setMinimumSize(QtCore.QSize(0, 31))
        self.le_hyfl.setObjectName(_fromUtf8("le_hyfl"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.le_hyfl)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(80, 31))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.le_ksdl = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_ksdl.setMinimumSize(QtCore.QSize(0, 31))
        self.le_ksdl.setObjectName(_fromUtf8("le_ksdl"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.le_ksdl)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(80, 31))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.le_gsdz = QtGui.QLineEdit(self.formLayoutWidget)
        self.le_gsdz.setMinimumSize(QtCore.QSize(0, 31))
        self.le_gsdz.setObjectName(_fromUtf8("le_gsdz"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.le_gsdz)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget)
        self.label_9.setMinimumSize(QtCore.QSize(80, 31))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_9)
        self.pte_sh = QtGui.QPlainTextEdit(self.formLayoutWidget)
        self.pte_sh.setMinimumSize(QtCore.QSize(0, 360))
        self.pte_sh.setObjectName(_fromUtf8("pte_sh"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.pte_sh)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.webView = QtWebKit.QWebView(Dialog)
        self.webView.setGeometry(QtCore.QRect(660, 60, 381, 691))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(660, 10, 381, 41))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2, QtCore.Qt.AlignHCenter)
        self.refreshweb = QtGui.QPushButton(self.horizontalLayoutWidget_2)
        self.refreshweb.setObjectName(_fromUtf8("refreshweb"))
        self.horizontalLayout_2.addWidget(self.refreshweb)
        self.pte_log = QtGui.QPlainTextEdit(Dialog)
        self.pte_log.setGeometry(QtCore.QRect(10, 560, 301, 191))
        self.pte_log.setReadOnly(True)
        self.pte_log.setObjectName(_fromUtf8("pte_log"))
        self.horizontalLayoutWidget_6 = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(320, 560, 331, 191))
        self.horizontalLayoutWidget_6.setObjectName(_fromUtf8("horizontalLayoutWidget_6"))
        self.verticalLayout = QtGui.QVBoxLayout(self.horizontalLayoutWidget_6)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pb_up1 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pb_up1.setObjectName(_fromUtf8("pb_up1"))
        self.verticalLayout.addWidget(self.pb_up1)
        self.pb_up2 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pb_up2.setObjectName(_fromUtf8("pb_up2"))
        self.verticalLayout.addWidget(self.pb_up2)
        self.pb_up3 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pb_up3.setObjectName(_fromUtf8("pb_up3"))
        self.verticalLayout.addWidget(self.pb_up3)
        self.pb_up4 = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pb_up4.setObjectName(_fromUtf8("pb_up4"))
        self.verticalLayout.addWidget(self.pb_up4)
        self.pb_giveup = QtGui.QPushButton(self.horizontalLayoutWidget_6)
        self.pb_giveup.setObjectName(_fromUtf8("pb_giveup"))
        self.verticalLayout.addWidget(self.pb_giveup)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.pb_deldata, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_deldata.click)
        QtCore.QObject.connect(self.pb_smb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_smb.click)
        QtCore.QObject.connect(self.pb_xmb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_xmb.click)
        QtCore.QObject.connect(self.pb_zmb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_zmb.click)
        QtCore.QObject.connect(self.pb_onebuild, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_onebuild.click)
        QtCore.QObject.connect(self.pb_upsybj, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upsybj.click)
        QtCore.QObject.connect(self.pb_upwz, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upwz.click)
        QtCore.QObject.connect(self.pb_upwz1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upwz1.click)
        QtCore.QObject.connect(self.pb_upwz2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upwz2.click)
        QtCore.QObject.connect(self.pb_upxc1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upxc1.click)
        QtCore.QObject.connect(self.pb_upxc2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upxc2.click)
        QtCore.QObject.connect(self.pb_up2, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_up2.click)
        QtCore.QObject.connect(self.pb_up3, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_up3.click)
        QtCore.QObject.connect(self.pte_log, QtCore.SIGNAL(_fromUtf8("textChanged()")), self.pte_log.selectAll)
        QtCore.QObject.connect(self.refreshweb, QtCore.SIGNAL(_fromUtf8("clicked()")), self.refreshweb.click)
        QtCore.QObject.connect(self.pb_upjj, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_upjj.click)
        QtCore.QObject.connect(self.pb_up4, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_up4.click)
        QtCore.QObject.connect(self.pb_up1, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_up1.click)
        QtCore.QObject.connect(self.pb_giveup, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_giveup.click)
        QtCore.QObject.connect(self.pb_scbjt, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_scbjt.click)
        QtCore.QObject.connect(self.pb_scfl, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_scfl.click)
        QtCore.QObject.connect(self.pb_scwz, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_scwz.click)
        QtCore.QObject.connect(self.pb_scxc, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_scxc.click)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.pb_deldata, self.le_xcfl1)
        Dialog.setTabOrder(self.le_xcfl1, self.pb_upxc1)
        Dialog.setTabOrder(self.pb_upxc1, self.le_xcfl2)
        Dialog.setTabOrder(self.le_xcfl2, self.pb_upxc2)
        Dialog.setTabOrder(self.pb_upxc2, self.le_fl1)
        Dialog.setTabOrder(self.le_fl1, self.le_fl2)
        Dialog.setTabOrder(self.le_fl2, self.le_fl3)
        Dialog.setTabOrder(self.le_fl3, self.pb_onebuild)
        Dialog.setTabOrder(self.pb_onebuild, self.le_wzfl1)
        Dialog.setTabOrder(self.le_wzfl1, self.pb_upwz1)
        Dialog.setTabOrder(self.pb_upwz1, self.le_wzfl2)
        Dialog.setTabOrder(self.le_wzfl2, self.pb_upwz2)
        Dialog.setTabOrder(self.pb_upwz2, self.pte_jj)
        Dialog.setTabOrder(self.pte_jj, self.pb_upjj)
        Dialog.setTabOrder(self.pb_upjj, self.refreshweb)
        Dialog.setTabOrder(self.refreshweb, self.pb_up1)
        Dialog.setTabOrder(self.pb_up1, self.pb_up2)
        Dialog.setTabOrder(self.pb_up2, self.pb_up3)
        Dialog.setTabOrder(self.pb_up3, self.pb_up4)
        Dialog.setTabOrder(self.pb_up4, self.pte_log)
        Dialog.setTabOrder(self.pte_log, self.webView)
        Dialog.setTabOrder(self.webView, self.le_gsjc)
        Dialog.setTabOrder(self.le_gsjc, self.tabWidget)
        Dialog.setTabOrder(self.tabWidget, self.le_ksdl)
        Dialog.setTabOrder(self.le_ksdl, self.le_hyfl)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "快速建站", None))
        self.pb_deldata.setText(_translate("Dialog", "清空数据", None))
        self.pb_scbjt.setText(_translate("Dialog", "删除背景图", None))
        self.pb_scfl.setText(_translate("Dialog", "删除分类", None))
        self.pb_scwz.setText(_translate("Dialog", "删除文章", None))
        self.pb_scxc.setText(_translate("Dialog", "删除相册", None))
        self.label_5.setText(_translate("Dialog", "文章", None))
        self.le_wzfl1.setText(_translate("Dialog", "行业动态", None))
        self.pb_upwz1.setText(_translate("Dialog", "上传文章1", None))
        self.le_wzfl2.setText(_translate("Dialog", "产品相关", None))
        self.pb_upwz2.setText(_translate("Dialog", "上传文章2", None))
        self.label_4.setText(_translate("Dialog", "相册", None))
        self.le_xcfl1.setText(_translate("Dialog", "相关展示", None))
        self.pb_upxc1.setText(_translate("Dialog", "上传相册1", None))
        self.le_xcfl2.setText(_translate("Dialog", "产品展示", None))
        self.pb_upxc2.setText(_translate("Dialog", "上传相册2", None))
        self.label_3.setText(_translate("Dialog", "分类", None))
        self.le_fl1.setText(_translate("Dialog", "公司简介", None))
        self.le_fl2.setText(_translate("Dialog", "相关资讯", None))
        self.le_fl3.setText(_translate("Dialog", "相关展示", None))
        self.pb_onebuild.setText(_translate("Dialog", "一键创建", None))
        self.label.setText(_translate("Dialog", "简介", None))
        self.pb_upwz.setText(_translate("Dialog", "上传文章", None))
        self.pb_upjj.setText(_translate("Dialog", "上传简介", None))
        self.pb_upsybj.setText(_translate("Dialog", "上传首页背景", None))
        self.pb_smb.setText(_translate("Dialog", "上模板", None))
        self.pb_xmb.setText(_translate("Dialog", "下模板", None))
        self.pb_zmb.setText(_translate("Dialog", "左模板", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "快速搭建", None))
        self.label_6.setText(_translate("Dialog", "公司简称", None))
        self.label_8.setText(_translate("Dialog", "黄页分类", None))
        self.label_7.setText(_translate("Dialog", "快速登录", None))
        self.label_11.setText(_translate("Dialog", "公司地址", None))
        self.label_9.setText(_translate("Dialog", "审　　核", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "企业信息", None))
        self.label_2.setText(_translate("Dialog", "实时视图", None))
        self.refreshweb.setText(_translate("Dialog", "刷新", None))
        self.pte_log.setPlainText(_translate("Dialog", "操作日志", None))
        self.pb_up1.setText(_translate("Dialog", "提交1.0", None))
        self.pb_up2.setText(_translate("Dialog", "提交2.0", None))
        self.pb_up3.setText(_translate("Dialog", "提交3.0", None))
        self.pb_up4.setText(_translate("Dialog", "提交4.0", None))
        self.pb_giveup.setText(_translate("Dialog", "放弃", None))

from PyQt4 import QtWebKit

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

