# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\python\���ٽ�վ\main.ui'
#
# Created: Tue Jun 30 19:32:57 2015
#    by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
  _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
  def _fromUtf8(s):
    return s

try:
  _encoding = QtGui.QApplication.UnicodeUTF8
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
  def _translate(context, text, disambig):
    return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
  def setupUi(self, MainWindow):
    MainWindow.setObjectName(_fromUtf8("MainWindow"))
    MainWindow.resize(909, 489)
    self.centralWidget = QtGui.QWidget(MainWindow)
    self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
    self.horizontalLayoutWidget = QtGui.QWidget(self.centralWidget)
    self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 611, 61))
    self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
    self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
    self.horizontalLayout.setMargin(0)
    self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
    self.pb_relogin = QtGui.QPushButton(self.horizontalLayoutWidget)
    self.pb_relogin.setObjectName(_fromUtf8("pb_relogin"))
    self.horizontalLayout.addWidget(self.pb_relogin)
    self.pb_refresh = QtGui.QPushButton(self.horizontalLayoutWidget)
    self.pb_refresh.setObjectName(_fromUtf8("pb_refresh"))
    self.horizontalLayout.addWidget(self.pb_refresh)
    self.pb_lastpage = QtGui.QPushButton(self.horizontalLayoutWidget)
    self.pb_lastpage.setObjectName(_fromUtf8("pb_lastpage"))
    self.horizontalLayout.addWidget(self.pb_lastpage)
    self.pb_nextpage = QtGui.QPushButton(self.horizontalLayoutWidget)
    self.pb_nextpage.setObjectName(_fromUtf8("pb_nextpage"))
    self.horizontalLayout.addWidget(self.pb_nextpage)
    self.table_oa = QtGui.QTableWidget(self.centralWidget)
    self.table_oa.setGeometry(QtCore.QRect(0, 60, 611, 421))
    self.table_oa.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
    self.table_oa.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
    self.table_oa.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
    self.table_oa.setObjectName(_fromUtf8("table_oa"))
    self.table_oa.setColumnCount(3)
    self.table_oa.setRowCount(25)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(0, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(1, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(2, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(3, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(4, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(5, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(6, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(7, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(8, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(9, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(10, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(11, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(12, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(13, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(14, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(15, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(16, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(17, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(18, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(19, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(20, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(21, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(22, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(23, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setVerticalHeaderItem(24, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setHorizontalHeaderItem(0, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setHorizontalHeaderItem(1, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setHorizontalHeaderItem(2, item)
    item = QtGui.QTableWidgetItem()
    self.table_oa.setItem(0, 0, item)
    self.table_oa.horizontalHeader().setVisible(True)
    self.table_oa.horizontalHeader().setCascadingSectionResizes(False)
    self.table_oa.horizontalHeader().setDefaultSectionSize(100)
    self.table_oa.horizontalHeader().setHighlightSections(True)
    self.table_oa.horizontalHeader().setMinimumSectionSize(25)
    self.table_oa.horizontalHeader().setSortIndicatorShown(False)
    self.table_oa.verticalHeader().setVisible(True)
    self.table_oa.verticalHeader().setDefaultSectionSize(30)
    self.table_oa.verticalHeader().setMinimumSectionSize(20)
    self.label = QtGui.QLabel(self.centralWidget)
    self.label.setGeometry(QtCore.QRect(621, -1, 281, 31))
    self.label.setObjectName(_fromUtf8("label"))
    self.pte_mainlog = QtGui.QPlainTextEdit(self.centralWidget)
    self.pte_mainlog.setGeometry(QtCore.QRect(620, 30, 281, 451))
    self.pte_mainlog.setObjectName(_fromUtf8("pte_mainlog"))
    MainWindow.setCentralWidget(self.centralWidget)

    self.retranslateUi(MainWindow)
    QtCore.QObject.connect(self.pb_relogin, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_relogin.click)
    QtCore.QObject.connect(self.pb_refresh, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_refresh.click)
    QtCore.QObject.connect(self.pb_lastpage, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_lastpage.click)
    QtCore.QObject.connect(self.pb_nextpage, QtCore.SIGNAL(_fromUtf8("clicked()")), self.pb_nextpage.click)
    QtCore.QObject.connect(self.table_oa, QtCore.SIGNAL(_fromUtf8("doubleClicked(QModelIndex)")), self.table_oa.edit)
    QtCore.QMetaObject.connectSlotsByName(MainWindow)

  def retranslateUi(self, MainWindow):
    MainWindow.setWindowTitle(_translate("MainWindow", "OA系统", None))
    self.pb_relogin.setText(_translate("MainWindow", "重新登录", None))
    self.pb_refresh.setText(_translate("MainWindow", "刷新", None))
    self.pb_lastpage.setText(_translate("MainWindow", "上一页", None))
    self.pb_nextpage.setText(_translate("MainWindow", "下一页", None))
    item = self.table_oa.verticalHeaderItem(0)
    item.setText(_translate("MainWindow", "1", None))
    item = self.table_oa.verticalHeaderItem(1)
    item.setText(_translate("MainWindow", "2", None))
    item = self.table_oa.verticalHeaderItem(2)
    item.setText(_translate("MainWindow", "3", None))
    item = self.table_oa.verticalHeaderItem(3)
    item.setText(_translate("MainWindow", "4", None))
    item = self.table_oa.verticalHeaderItem(4)
    item.setText(_translate("MainWindow", "5", None))
    item = self.table_oa.verticalHeaderItem(5)
    item.setText(_translate("MainWindow", "6", None))
    item = self.table_oa.verticalHeaderItem(6)
    item.setText(_translate("MainWindow", "7", None))
    item = self.table_oa.verticalHeaderItem(7)
    item.setText(_translate("MainWindow", "8", None))
    item = self.table_oa.verticalHeaderItem(8)
    item.setText(_translate("MainWindow", "9", None))
    item = self.table_oa.verticalHeaderItem(9)
    item.setText(_translate("MainWindow", "10", None))
    item = self.table_oa.verticalHeaderItem(10)
    item.setText(_translate("MainWindow", "11", None))
    item = self.table_oa.verticalHeaderItem(11)
    item.setText(_translate("MainWindow", "12", None))
    item = self.table_oa.verticalHeaderItem(12)
    item.setText(_translate("MainWindow", "13", None))
    item = self.table_oa.verticalHeaderItem(13)
    item.setText(_translate("MainWindow", "14", None))
    item = self.table_oa.verticalHeaderItem(14)
    item.setText(_translate("MainWindow", "15", None))
    item = self.table_oa.verticalHeaderItem(15)
    item.setText(_translate("MainWindow", "16", None))
    item = self.table_oa.verticalHeaderItem(16)
    item.setText(_translate("MainWindow", "17", None))
    item = self.table_oa.verticalHeaderItem(17)
    item.setText(_translate("MainWindow", "18", None))
    item = self.table_oa.verticalHeaderItem(18)
    item.setText(_translate("MainWindow", "19", None))
    item = self.table_oa.verticalHeaderItem(19)
    item.setText(_translate("MainWindow", "20", None))
    item = self.table_oa.verticalHeaderItem(20)
    item.setText(_translate("MainWindow", "21", None))
    item = self.table_oa.verticalHeaderItem(21)
    item.setText(_translate("MainWindow", "22", None))
    item = self.table_oa.verticalHeaderItem(22)
    item.setText(_translate("MainWindow", "23", None))
    item = self.table_oa.verticalHeaderItem(23)
    item.setText(_translate("MainWindow", "24", None))
    item = self.table_oa.verticalHeaderItem(24)
    item.setText(_translate("MainWindow", "25", None))
    item = self.table_oa.horizontalHeaderItem(0)
    item.setText(_translate("MainWindow", "公司名称", None))
    item = self.table_oa.horizontalHeaderItem(1)
    item.setText(_translate("MainWindow", "建站人", None))
    item = self.table_oa.horizontalHeaderItem(2)
    item.setText(_translate("MainWindow", "审核人", None))
    __sortingEnabled = self.table_oa.isSortingEnabled()
    self.table_oa.setSortingEnabled(False)
    self.table_oa.setSortingEnabled(__sortingEnabled)
    self.label.setText(_translate("MainWindow", "操作日志", None))


if __name__ == "__main__":
  import sys
  app = QtGui.QApplication(sys.argv)
  MainWindow = QtGui.QMainWindow()
  ui = Ui_MainWindow()
  ui.setupUi(MainWindow)
  MainWindow.show()
  sys.exit(app.exec_())

